/**
 * Pause/resume billing adjustment engine (Issue #1116).
 *
 * When a subscription is paused the unused portion of the current billing
 * period is converted into a credit that is applied to the next invoice.
 * Resuming early returns the unconsumed part of that credit.
 *
 * All calculations are pure so they can be unit tested without a database.
 */

export type PauseReason = 'vacation' | 'financial_hardship' | 'temporary_need' | 'other';

export interface PauseLimits {
  minDays: number;
  maxDays: number;
  maxPausesPerYear: number;
}

export interface PauseBillingInput {
  subscriptionId: string;
  price: number;
  currency: string;
  /** Length of the billing period in days (30 monthly / 365 yearly). */
  periodDays: number;
  pauseDays: number;
}

export interface PauseBillingAdjustment {
  subscriptionId: string;
  currency: string;
  pauseDays: number;
  periodDays: number;
  /** Credit generated by the pause, rounded to 2 decimals. */
  creditAmount: number;
  /** Credit that survives an immediate early resume (equal to creditAmount). */
  earlyResumeCredit: number;
  /** Credit still available on the record right after pausing. */
  creditRemaining: number;
  /** Net amount still owed for the current period after the credit. */
  remainingBalance: number;
  /** Days of credit that expire if the subscription is never resumed. */
  creditExpiryDays: number;
}

export interface ResumeBillingInput {
  creditAmount: number;
  pauseDays: number;
  daysElapsed: number;
}

export interface ResumeBillingAdjustment {
  creditConsumed: number;
  creditRefund: number;
  creditRemaining: number;
}

export const DEFAULT_PAUSE_LIMITS: PauseLimits = {
  minDays: 7,
  maxDays: 90,
  maxPausesPerYear: 2,
};

export const CREDIT_EXPIRY_DAYS = 90;
const MS_PER_DAY = 24 * 60 * 60 * 1000;

function round2(value: number): number {
  return Math.round(value * 100) / 100;
}

/** Days in a billing period. */
export function getPeriodDays(billingCycle: string): number {
  return billingCycle === 'yearly' || billingCycle === 'annual' ? 365 : 30;
}

/**
 * Credit generated by pausing: (pauseDays / periodDays) * price.
 * Never exceeds the price of the period and never goes negative.
 */
export function calculatePauseCredit(
  input: Pick<PauseBillingInput, 'price' | 'periodDays' | 'pauseDays'>
): number {
  const { price, periodDays, pauseDays } = input;
  if (price <= 0 || periodDays <= 0 || pauseDays <= 0) return 0;
  return round2(Math.min(price, (pauseDays / periodDays) * price));
}

/**
 * Credit refunded when the subscription resumes before the scheduled date.
 * Consumed credit = (daysElapsed / pauseDays) * creditAmount.
 */
export function calculateResumeCredit(input: ResumeBillingInput): ResumeBillingAdjustment {
  const { creditAmount, pauseDays, daysElapsed } = input;
  const safePauseDays = Math.max(1, pauseDays);
  const elapsed = Math.min(Math.max(0, daysElapsed), safePauseDays);
  const creditConsumed = round2((elapsed / safePauseDays) * creditAmount);
  return {
    creditConsumed,
    creditRefund: round2(creditAmount - creditConsumed),
    creditRemaining: round2(creditAmount - creditConsumed),
  };
}

/** Validate a pause request against the configured limits. */
export function validatePauseRequest(
  pauseDays: number,
  activePauseExists: boolean,
  pausesThisYear: number,
  limits: PauseLimits = DEFAULT_PAUSE_LIMITS
): { valid: boolean; reason?: string } {
  if (!Number.isFinite(pauseDays) || pauseDays <= 0) {
    return { valid: false, reason: 'Pause duration must be a positive number of days.' };
  }
  if (activePauseExists) {
    return { valid: false, reason: 'This subscription is already paused.' };
  }
  if (pauseDays < limits.minDays) {
    return { valid: false, reason: `Minimum pause duration is ${limits.minDays} days.` };
  }
  if (pauseDays > limits.maxDays) {
    return { valid: false, reason: `Maximum pause duration is ${limits.maxDays} days.` };
  }
  if (pausesThisYear >= limits.maxPausesPerYear) {
    return {
      valid: false,
      reason: `Maximum of ${limits.maxPausesPerYear} pauses per year reached.`,
    };
  }
  return { valid: true };
}

/**
 * Build the full billing adjustment produced by a pause, including the
 * remaining balance owed for the current period.
 */
export function buildPauseBillingAdjustment(input: PauseBillingInput): PauseBillingAdjustment {
  const creditAmount = calculatePauseCredit(input);
  const remainingBalance = round2(Math.max(0, input.price - creditAmount));

  return {
    subscriptionId: input.subscriptionId,
    currency: input.currency,
    pauseDays: input.pauseDays,
    periodDays: input.periodDays,
    creditAmount,
    earlyResumeCredit: creditAmount,
    creditRemaining: creditAmount,
    remainingBalance,
    creditExpiryDays: CREDIT_EXPIRY_DAYS,
  };
}

/** ISO timestamp `days` in the future. */
export function daysFromNow(days: number, from: Date = new Date()): string {
  return new Date(from.getTime() + days * MS_PER_DAY).toISOString();
}

/** Whether a scheduled resume date has passed. */
export function isResumeDue(scheduledResumeAt: Date | string, now: Date = new Date()): boolean {
  const target = typeof scheduledResumeAt === 'string' ? new Date(scheduledResumeAt) : scheduledResumeAt;
  return target.getTime() <= now.getTime();
}

/** Whole days elapsed between two instants, never negative. */
export function daysBetween(from: Date | string, to: Date | string = new Date()): number {
  const start = typeof from === 'string' ? new Date(from) : from;
  const end = typeof to === 'string' ? new Date(to) : to;
  return Math.max(0, Math.floor((end.getTime() - start.getTime()) / MS_PER_DAY));
}
