packages:
  - packages/notification-providers
  - services/notification

allowBuilds:
  '@parcel/watcher': true
  bufferutil: false
  detox: false
  dtrace-provider: false
  es5-ext: false
  esbuild: true
  keccak: false
  secp256k1: false
  unrs-resolver: false
  utf-8-validate: false
  web3: false
  web3-bzz: false
  web3-shh: false
