export enum SimulationErrorCode {
  INSUFFICIENT_BALANCE = 'INSUFFICIENT_BALANCE',
  AUTH_MISMATCH = 'AUTH_MISMATCH',
  CONTRACT_ERROR = 'CONTRACT_ERROR',
  EXPIRED_ENTRY = 'EXPIRED_ENTRY',
  INVALID_STATE = 'INVALID_STATE',
  INSUFFICIENT_GAS = 'INSUFFICIENT_GAS',
  SEQUENCE_ERROR = 'SEQUENCE_ERROR',
  NETWORK_ERROR = 'NETWORK_ERROR',
  UNKNOWN = 'UNKNOWN',
}
