"""ETL pipeline monitoring and alerting."""

import logging
import time
from collections import deque
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Dict, List, Optional

from .config import MonitoringConfig

logger = logging.getLogger(__name__)


@dataclass
class PipelineMetrics:
    """Metrics for a single pipeline execution."""
    start_time: float = 0.0
    end_time: float = 0.0
    duration_ms: float = 0.0
    records_extracted: int = 0
    records_transformed: int = 0
    records_loaded: int = 0
    success: bool = False
    error_count: int = 0
    errors: List[str] = field(default_factory=list)
    timestamp: str = field(default_factory=lambda: datetime.now().isoformat())


@dataclass
class Alert:
    """An alert generated by the monitoring system."""
    level: str  # "warning", "error", "critical"
    message: str
    metric_name: str
    value: float
    threshold: float
    timestamp: str = field(default_factory=lambda: datetime.now().isoformat())


class ETLMonitor:
    """Monitors ETL pipeline execution, tracks metrics, and generates alerts."""

    def __init__(self, config: Optional[MonitoringConfig] = None):
        self.config = config or MonitoringConfig()
        self._metrics_history: deque = deque(maxlen=1000)
        self._alerts: List[Alert] = []
        self._counters: Dict[str, int] = {
            "total_runs": 0,
            "successful_runs": 0,
            "failed_runs": 0,
            "total_records_processed": 0,
            "total_errors": 0,
        }
        self._current_run: Optional[PipelineMetrics] = None

    def record_pipeline_start(self):
        self._current_run = PipelineMetrics(start_time=time.time())

    def record_pipeline_end(self, result: Any):
        if self._current_run is None:
            return

        self._current_run.end_time = time.time()
        self._current_run.duration_ms = (self._current_run.end_time - self._current_run.start_time) * 1000
        self._current_run.records_extracted = getattr(result, "records_extracted", 0)
        self._current_run.records_transformed = getattr(result, "records_transformed", 0)
        self._current_run.records_loaded = getattr(result, "records_loaded", 0)
        self._current_run.success = getattr(result, "success", False)
        self._current_run.errors = getattr(result, "errors", [])
        self._current_run.error_count = len(self._current_run.errors)

        self._metrics_history.append(self._current_run)
        self._update_counters(self._current_run)
        self._check_thresholds(self._current_run)

    def _update_counters(self, metrics: PipelineMetrics):
        self._counters["total_runs"] += 1
        if metrics.success:
            self._counters["successful_runs"] += 1
        else:
            self._counters["failed_runs"] += 1
        self._counters["total_records_processed"] += metrics.records_loaded
        self._counters["total_errors"] += metrics.error_count

    def _check_thresholds(self, metrics: PipelineMetrics):
        if not self.config.enabled:
            return

        if metrics.duration_ms > self.config.alert_threshold_ms:
            self._alerts.append(Alert(
                level="warning",
                message=f"Pipeline took {metrics.duration_ms:.0f}ms (threshold: {self.config.alert_threshold_ms}ms)",
                metric_name="duration_ms",
                value=metrics.duration_ms,
                threshold=self.config.alert_threshold_ms,
            ))

        total_runs = self._counters["total_runs"]
        if total_runs > 10:
            error_rate = self._counters["failed_runs"] / total_runs
            if error_rate > self.config.error_rate_threshold:
                self._alerts.append(Alert(
                    level="error",
                    message=f"Error rate {error_rate:.1%} exceeds threshold {self.config.error_rate_threshold:.1%}",
                    metric_name="error_rate",
                    value=error_rate,
                    threshold=self.config.error_rate_threshold,
                ))

    def log_pipeline_result(self, result: Any):
        success = getattr(result, "success", False)
        duration = getattr(result, "duration_ms", 0)
        extracted = getattr(result, "records_extracted", 0)
        loaded = getattr(result, "records_loaded", 0)

        if success:
            logger.info(
                f"Pipeline completed in {duration:.0f}ms: "
                f"{extracted} extracted, {loaded} loaded"
            )
        else:
            errors = getattr(result, "errors", [])
            logger.error(f"Pipeline failed in {duration:.0f}ms: {errors}")

    def get_metrics_summary(self) -> Dict[str, Any]:
        recent = list(self._metrics_history)[-10:]
        durations = [m.duration_ms for m in recent]
        return {
            "total_runs": self._counters["total_runs"],
            "successful_runs": self._counters["successful_runs"],
            "failed_runs": self._counters["failed_runs"],
            "success_rate": (
                self._counters["successful_runs"] / max(self._counters["total_runs"], 1)
            ),
            "total_records_processed": self._counters["total_records_processed"],
            "total_errors": self._counters["total_errors"],
            "avg_duration_ms": sum(durations) / max(len(durations), 1),
            "recent_alerts": len(self._alerts),
            "active_alerts": [a.__dict__ for a in self._alerts[-5:]],
        }

    def get_alerts(self, level: Optional[str] = None) -> List[Alert]:
        if level is None:
            return list(self._alerts)
        return [a for a in self._alerts if a.level == level]

    def clear_alerts(self):
        self._alerts.clear()
