import { FeatureConfig, FeatureId, UserSegment } from '../types/feature';
import { SubscriptionTier } from '../types/subscription';

export const USER_SEGMENTS: UserSegment[] = [
  {
    id: 'beta_testers',
    name: 'Beta Testers',
    conditions: [{ attribute: 'isBetaTester', operator: 'eq', value: true }],
    matchAll: true,
  },
  {
    id: 'staff',
    name: 'Staff Members',
    conditions: [{ attribute: 'isStaff', operator: 'eq', value: true }],
    matchAll: true,
  },
  {
    id: 'new_users',
    name: 'New Users',
    conditions: [{ attribute: 'isNewUser', operator: 'eq', value: true }],
    matchAll: true,
  },
  {
    id: 'us_region',
    name: 'US Region',
    conditions: [{ attribute: 'region', operator: 'eq', value: 'us' }],
    matchAll: true,
  },
  {
    id: 'high_usage',
    name: 'High Usage Users',
    conditions: [{ attribute: 'totalSubscriptions', operator: 'gte', value: 10 }],
    matchAll: true,
  },
  {
    id: 'enterprise_tier',
    name: 'Enterprise Tier',
    conditions: [{ attribute: 'tier', operator: 'eq', value: SubscriptionTier.ENTERPRISE }],
    matchAll: true,
  },
];

export const FEATURE_CONFIG: FeatureConfig = {
  globalRolloutPercentage: 100,
  abTestEnabled: true,
  segments: USER_SEGMENTS,
  killSwitch: {
    active: false,
    overrides: {},
  },
  plans: {
    [SubscriptionTier.FREE]: [
      FeatureId.BASIC_SUBSCRIPTION_TRACKING,
      FeatureId.BASIC_ANALYTICS,
      FeatureId.PUSH_NOTIFICATIONS,
    ],
    [SubscriptionTier.BASIC]: [
      FeatureId.BASIC_SUBSCRIPTION_TRACKING,
      FeatureId.BASIC_ANALYTICS,
      FeatureId.PUSH_NOTIFICATIONS,
      FeatureId.BUDGET_ALERTS,
      FeatureId.EXPORT_DATA,
    ],
    [SubscriptionTier.PREMIUM]: [
      FeatureId.BASIC_SUBSCRIPTION_TRACKING,
      FeatureId.BASIC_ANALYTICS,
      FeatureId.PUSH_NOTIFICATIONS,
      FeatureId.BUDGET_ALERTS,
      FeatureId.EXPORT_DATA,
      FeatureId.ADVANCED_ANALYTICS,
      FeatureId.MULTI_CURRENCY,
      FeatureId.CRYPTO_INTEGRATION,
    ],
    [SubscriptionTier.ENTERPRISE]: [
      FeatureId.BASIC_SUBSCRIPTION_TRACKING,
      FeatureId.BASIC_ANALYTICS,
      FeatureId.PUSH_NOTIFICATIONS,
      FeatureId.BUDGET_ALERTS,
      FeatureId.EXPORT_DATA,
      FeatureId.ADVANCED_ANALYTICS,
      FeatureId.MULTI_CURRENCY,
      FeatureId.CRYPTO_INTEGRATION,
      FeatureId.TEAM_COLLABORATION,
      FeatureId.CUSTOM_REPORTS,
      FeatureId.API_ACCESS,
      FeatureId.PRIORITY_SUPPORT,
      FeatureId.WHITE_LABEL,
      FeatureId.DEVELOPER_PORTAL,
      FeatureId.SANDBOX_ACCESS,
    ],
  },
  features: {
    [FeatureId.BASIC_SUBSCRIPTION_TRACKING]: {
      id: FeatureId.BASIC_SUBSCRIPTION_TRACKING,
      name: 'Basic Subscription Tracking',
      description: 'Track your subscriptions with basic features',
      enabled: true,
      tierAccess: [
        SubscriptionTier.FREE,
        SubscriptionTier.BASIC,
        SubscriptionTier.PREMIUM,
        SubscriptionTier.ENTERPRISE,
      ],
      rolloutPercentage: 100,
      rolloutStages: [
        { percentage: 10, label: 'internal_testing', createdAt: new Date('2024-01-01') },
        { percentage: 25, label: 'closed_beta', createdAt: new Date('2024-01-05') },
        { percentage: 50, label: 'open_beta', createdAt: new Date('2024-01-10') },
        { percentage: 100, label: 'general_availability', createdAt: new Date('2024-01-15') },
      ],
      createdAt: new Date('2024-01-01'),
      updatedAt: new Date('2024-01-15'),
    },
    [FeatureId.BASIC_ANALYTICS]: {
      id: FeatureId.BASIC_ANALYTICS,
      name: 'Basic Analytics',
      description: 'View basic spending analytics and insights',
      enabled: true,
      tierAccess: [
        SubscriptionTier.FREE,
        SubscriptionTier.BASIC,
        SubscriptionTier.PREMIUM,
        SubscriptionTier.ENTERPRISE,
      ],
      rolloutPercentage: 100,
      rolloutStages: [
        { percentage: 10, label: 'internal_testing', createdAt: new Date('2024-01-01') },
        { percentage: 25, label: 'closed_beta', createdAt: new Date('2024-01-05') },
        { percentage: 50, label: 'open_beta', createdAt: new Date('2024-01-10') },
        { percentage: 100, label: 'general_availability', createdAt: new Date('2024-01-15') },
      ],
      createdAt: new Date('2024-01-01'),
      updatedAt: new Date('2024-01-15'),
    },
    [FeatureId.PUSH_NOTIFICATIONS]: {
      id: FeatureId.PUSH_NOTIFICATIONS,
      name: 'Push Notifications',
      description: 'Receive notifications about subscription renewals and payments',
      enabled: true,
      tierAccess: [
        SubscriptionTier.FREE,
        SubscriptionTier.BASIC,
        SubscriptionTier.PREMIUM,
        SubscriptionTier.ENTERPRISE,
      ],
      rolloutPercentage: 100,
      rolloutStages: [
        { percentage: 10, label: 'internal_testing', createdAt: new Date('2024-01-01') },
        { percentage: 25, label: 'closed_beta', createdAt: new Date('2024-01-05') },
        { percentage: 50, label: 'open_beta', createdAt: new Date('2024-01-10') },
        { percentage: 100, label: 'general_availability', createdAt: new Date('2024-01-15') },
      ],
      createdAt: new Date('2024-01-01'),
      updatedAt: new Date('2024-01-15'),
    },
    [FeatureId.BUDGET_ALERTS]: {
      id: FeatureId.BUDGET_ALERTS,
      name: 'Budget Alerts',
      description: 'Set spending limits and receive alerts when approaching them',
      enabled: true,
      tierAccess: [SubscriptionTier.BASIC, SubscriptionTier.PREMIUM, SubscriptionTier.ENTERPRISE],
      dependencies: [FeatureId.BASIC_SUBSCRIPTION_TRACKING],
      rolloutPercentage: 100,
      rolloutStages: [
        { percentage: 10, label: 'internal_testing', createdAt: new Date('2024-01-01') },
        { percentage: 25, label: 'closed_beta', createdAt: new Date('2024-01-05') },
        { percentage: 50, label: 'open_beta', createdAt: new Date('2024-01-10') },
        { percentage: 100, label: 'general_availability', createdAt: new Date('2024-01-15') },
      ],
      createdAt: new Date('2024-01-01'),
      updatedAt: new Date('2024-01-15'),
    },
    [FeatureId.EXPORT_DATA]: {
      id: FeatureId.EXPORT_DATA,
      name: 'Export Data',
      description: 'Export your subscription data in various formats',
      enabled: true,
      tierAccess: [SubscriptionTier.BASIC, SubscriptionTier.PREMIUM, SubscriptionTier.ENTERPRISE],
      dependencies: [FeatureId.BASIC_SUBSCRIPTION_TRACKING],
      rolloutPercentage: 100,
      createdAt: new Date('2024-01-01'),
      updatedAt: new Date('2024-01-01'),
    },
    [FeatureId.ADVANCED_ANALYTICS]: {
      id: FeatureId.ADVANCED_ANALYTICS,
      name: 'Advanced Analytics',
      description: 'Detailed spending trends, forecasting, and category insights',
      enabled: true,
      tierAccess: [SubscriptionTier.PREMIUM, SubscriptionTier.ENTERPRISE],
      dependencies: [FeatureId.BASIC_ANALYTICS],
      rolloutPercentage: 100,
      segments: ['beta_testers', 'staff'],
      createdAt: new Date('2024-01-01'),
      updatedAt: new Date('2024-01-01'),
    },
    [FeatureId.MULTI_CURRENCY]: {
      id: FeatureId.MULTI_CURRENCY,
      name: 'Multi-Currency Support',
      description: 'Track subscriptions in multiple currencies with automatic conversion',
      enabled: true,
      tierAccess: [SubscriptionTier.PREMIUM, SubscriptionTier.ENTERPRISE],
      rolloutPercentage: 100,
      createdAt: new Date('2024-01-01'),
      updatedAt: new Date('2024-01-01'),
    },
    [FeatureId.CRYPTO_INTEGRATION]: {
      id: FeatureId.CRYPTO_INTEGRATION,
      name: 'Crypto Integration',
      description: 'Pay subscriptions with cryptocurrency and track crypto holdings',
      enabled: true,
      tierAccess: [SubscriptionTier.PREMIUM, SubscriptionTier.ENTERPRISE],
      rolloutPercentage: 75,
      segments: ['us_region'],
      createdAt: new Date('2024-01-01'),
      updatedAt: new Date('2024-06-01'),
    },
    [FeatureId.TEAM_COLLABORATION]: {
      id: FeatureId.TEAM_COLLABORATION,
      name: 'Team Collaboration',
      description: 'Share subscription management with team members',
      enabled: true,
      tierAccess: [SubscriptionTier.ENTERPRISE],
      rolloutPercentage: 50,
      rolloutStages: [
        { percentage: 10, label: 'internal_testing', createdAt: new Date('2024-03-01') },
        { percentage: 25, label: 'closed_beta', createdAt: new Date('2024-04-01') },
        { percentage: 50, label: 'open_beta', createdAt: new Date('2024-05-01') },
      ],
      segments: ['beta_testers', 'enterprise_tier'],
      createdAt: new Date('2024-03-01'),
      updatedAt: new Date('2024-05-01'),
    },
    [FeatureId.CUSTOM_REPORTS]: {
      id: FeatureId.CUSTOM_REPORTS,
      name: 'Custom Reports',
      description: 'Create and schedule custom subscription reports',
      enabled: true,
      tierAccess: [SubscriptionTier.ENTERPRISE],
      dependencies: [FeatureId.ADVANCED_ANALYTICS],
      rolloutPercentage: 25,
      rolloutStages: [
        { percentage: 10, label: 'internal_testing', createdAt: new Date('2024-04-01') },
        { percentage: 25, label: 'closed_beta', createdAt: new Date('2024-05-01') },
      ],
      segments: ['beta_testers', 'staff'],
      createdAt: new Date('2024-04-01'),
      updatedAt: new Date('2024-05-01'),
    },
    [FeatureId.API_ACCESS]: {
      id: FeatureId.API_ACCESS,
      name: 'API Access',
      description: 'Access subscription data via REST API for integrations',
      enabled: true,
      tierAccess: [SubscriptionTier.ENTERPRISE],
      rolloutPercentage: 100,
      createdAt: new Date('2024-01-01'),
      updatedAt: new Date('2024-01-01'),
    },
    [FeatureId.PRIORITY_SUPPORT]: {
      id: FeatureId.PRIORITY_SUPPORT,
      name: 'Priority Support',
      description: 'Get faster response times and dedicated support',
      enabled: true,
      tierAccess: [SubscriptionTier.ENTERPRISE],
      rolloutPercentage: 100,
      createdAt: new Date('2024-01-01'),
      updatedAt: new Date('2024-01-01'),
    },
    [FeatureId.WHITE_LABEL]: {
      id: FeatureId.WHITE_LABEL,
      name: 'White Label',
      description: 'Customize the app branding for your organization',
      enabled: true,
      tierAccess: [SubscriptionTier.ENTERPRISE],
      rolloutPercentage: 100,
      createdAt: new Date('2024-01-01'),
      updatedAt: new Date('2024-01-01'),
    },
    [FeatureId.DEVELOPER_PORTAL]: {
      id: FeatureId.DEVELOPER_PORTAL,
      name: 'Developer Portal',
      description:
        'Access the developer portal with API documentation, integration guides, and sandbox environment',
      enabled: true,
      tierAccess: [SubscriptionTier.ENTERPRISE],
      rolloutPercentage: 100,
      createdAt: new Date('2024-01-01'),
      updatedAt: new Date('2024-01-01'),
    },
    [FeatureId.SANDBOX_ACCESS]: {
      id: FeatureId.SANDBOX_ACCESS,
      name: 'Sandbox Access',
      description: 'Access isolated sandbox environment for testing integrations with test data',
      enabled: true,
      tierAccess: [SubscriptionTier.ENTERPRISE],
      dependencies: [FeatureId.API_ACCESS],
      rolloutPercentage: 100,
      createdAt: new Date('2024-01-01'),
      updatedAt: new Date('2024-01-01'),
    },
  },
};
