export { CampaignService } from './campaignService';
export type { Campaign, CouponCode, PromotionRule, CampaignTargeting, StackingConfig, CampaignAnalytics, CampaignOverlap, CouponValidation } from './campaignService';
export { generateComplianceReport, formatComplianceReport } from './complianceReport';
export type { ComplianceReport, EncryptionStatus, KeyManagementStatus, PiiAccessSummary, DataMaskingStatus } from './complianceReport';
export { DataPipelineService } from './dataPipeline';
export { DataWarehouseService } from './dataWarehouse';
export { PredictionService } from './predictionService';
export type { ChurnPrediction, RiskFactor, UserChurnData, ForecastPoint, RevenueObservation } from './predictionService';
export { RecommendationService } from './recommendationService';
export type { Recommendation, RecommendationContext } from './recommendationService';
export { RetentionService } from './retentionService';
export { OracleMonitorService, oracleMonitorService } from './oracleMonitorService';
export type { IPredictionService, IRecommendationService, IComplianceReportService, ICampaignService } from './interfaces';
export { AnalyticsError, AnalyticsErrorCode } from './errors';
