name: CI/CD Pipeline

on:
  push:
    branches: [main, dev, develop, 'feature/*']
  pull_request:
    branches: [main, dev, develop, 'feature/*']

jobs:
  ci:
    uses: ./.github/workflows/ci-core.yml
    secrets: inherit
